-- Organization join codes for self-service signup (admin shares code with staff).

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS join_code TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS organizations_join_code_unique_idx
  ON organizations (join_code)
  WHERE join_code IS NOT NULL;

ALTER TABLE org_license
  ADD COLUMN IF NOT EXISTS max_seats INTEGER;

COMMENT ON COLUMN organizations.join_code IS
  'Unique code staff enter at /join to self-register into this org. Regenerated by platform admins.';

COMMENT ON COLUMN org_license.max_seats IS
  'Optional seat cap for join-code and invite signups. NULL = no limit enforced.';
